version: 2.1

orbs:
  go: gotest/tools@0.0.13

workflows:
  ci:
    jobs:
      - go/test:
          name: test-golang-1.16-alpine
          go-test-flags: "-count=1 -p=4"
          gotestsum-format: standard-verbose
          executor:
            name: go/golang
            tag:  "1.16-alpine"

      - go/test:
          name: test-golang-1.16-deb
          go-test-flags: "-count=1 -p=4"
          gotestsum-format: standard-verbose
          executor:
            name: go/golang
            tag:  "1.16"
